### ISSUE TITLE
browserified version?

### ISSUE THREAD

**Issue by seiyria** [a-type/adjective-adjective-animal#7]
it'd be great if there were a browserified version readily available for installation (possibly via bower)

**Comment by a-type** [comment]
I'm not too familiar with how to package distributed browserified versions. Would this just be a `/dist/` folder with the minified/unminified compiled JS, and listing it on Bower?

**Comment by seiyria** [comment]
Essentially yes, that's all there is to it.

**Comment by a-type** [comment]
Great. I'll get on that.

**Comment by a-type** [comment]
Initial report: this is trickier than it seems, since the library is not browserify-able in it's current state, since I chose to load the lists with `fs` instead of using `require`. I'm reworking it, but will have to rewrite some of the testing as well.

**Comment by a-type** [comment]
Released as v1.4.0!
